#ifndef C_COMPILER_ABSTRACT_TREE_H
#define C_COMPILER_ABSTRACT_TREE_H

enum pt_enum_exp {
    PT_ENUM_EXP_EXPEMIC,
    PT_ENUM_EXP_INTVAL,
    PT_ENUM_EXP_FLOATVAL,
    PT_ENUM_EXP_NEG,
    PT_ENUM_EXP_PLUS,
    PT_ENUM_EXP_MINUS,
    PT_ENUM_EXP_MUL,
    PT_ENUM_EXP_DIV,
    PT_ENUM_EXP_EQ,
    PT_ENUM_EXP_GE,
    PT_ENUM_EXP_LE,
    PT_ENUM_EXP_NEQ,
    PT_ENUM_EXP_GT,
    PT_ENUM_EXP_LT,
    PT_ENUM_EXP_AND,
    PT_ENUM_EXP_OR,
    PT_ENUM_EXP_ASSIGN,
    PT_ENUM_EXP_IF,
    PT_ENUM_EXP_IFELSE,
    PT_ENUM_EXP_WHILE 
};



#endif
