#ifndef C_COMPILER_ABSTRACT_TREE_H
#define C_COMPILER_ABSTRACT_TREE_H

enum enum_exp
{
    ENUM_EXP_EXPITERSEMIC,
    ENUM_EXP_INTVAL,
    ENUM_EXP_REALVAL,
    ENUM_EXP_STRINGVAL,
    ENUM_EXP_NEG,
    ENUM_EXP_PLUS,
    ENUM_EXP_MINUS,
    ENUM_EXP_MULTIPLY,
    ENUM_EXP_DIVIDE,
    ENUM_EXP_EQUALS,
    ENUM_EXP_GE,
    ENUM_EXP_LE,
    ENUM_EXP_DIFFERENT,
    ENUM_EXP_GT,
    ENUM_EXP_LT,
    ENUM_EXP_AND,
    ENUM_EXP_OR,
    ENUM_EXP_LVALUE,
    ENUM_EXP_AFFECT,
    ENUM_EXP_IF,
    ENUM_EXP_IFELSE,
    ENUM_EXP_WHILE,
    ENUM_EXP_FOR,
    ENUM_EXP_LET,
    ENUM_EXP_EXPITERID
};

#endif
